import Head from 'next/head';
import Image from 'components/base/image';
import styles from 'styles/Home.module.css';
import NavigationBar from 'components/layout/navigation';
import Button from 'components/base/button';
import HomePage from 'pages/sections/home';
import AboutPage from 'pages/sections/about';
import KucingSlide from 'pages/sections/kucingSlide';
import Rarity from 'pages/sections/rarity';
import TextInput from 'components/base/textInput';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ball Lickin Cat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${process.env.image_cdn}images/favicon.ico`} />
        <link
          rel="stylesheet"
          href="https://unpkg.com/swiper/css/swiper.min.css"
        />
      </Head>
      <div className="min-h-[100vh] bg-[url('https://cdn.ball-lickincats.com/images/bg-home-section-backup.png')] bg-bottom bg-no-repeat">
        <div className="container mx-auto pt-[100px] pb-[400px]">
          <div className="flex flex-col items-center">
            <Image
              source={`${process.env.image_cdn}images/kucingangkattangan.png`}
              className="w-[200px] mb-[-30px]"
            />
            <h1 className="text-l text-center font-bold text-nileblue leading-none bg-broom rounded-2xl px-[20px] py-[5px] z-10">
              PRE SALE<br></br>LIVE
            </h1>
            <div className="flex flex-col min-w-[500px] bg-nileblue bg-opacity-50 rounded-2xl pt-[50px] px-[15px] mt-[-30px]">
              <div className="flex flex-row">
                <Image
                  source={`${process.env.image_cdn}images/kucingangkattangan.png`}
                  className="w-[200px]"
                />
                <div>
                  <div>WALLET ADDRESS :</div>
                  <div>jdsfjsle383je0932948wdjsdgsdajdd</div>
                  <div>Not Whitelisted</div>
                  <div>Price Per Cat</div>
                  <div>
                    <span>1000 </span>
                    <span>ETH / Each</span>
                  </div>
                </div>
              </div>
              <div>
                <Button text={'MINT'} />
                <TextInput />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
