import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import NavigationBar from 'components/layout/navigation';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ball Lickin Cat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${process.env.image_cdn}images/favicon.ico`} />
      </Head>
      <NavigationBar />
    </div>
  )
}
