import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import NavigationBar from 'components/layout/navigation';
import Button from 'components/base/button';
import HomePage from 'pages/sections/home';
import AboutPage from 'pages/sections/about';
import KucingSlide from 'pages/sections/kucingSlide';
import Rarity from 'pages/sections/rarity';

export default function Home() {
  return (
    <>
      <Head>
      <title>Ball Lickin Cat</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={`${process.env.image_cdn}images/favicon.ico`} />
      <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css" />
      </Head>
      <div className="h-[100vh] bg-[url('https://cdn.ball-lickincats.com/images/bg-home-section-backup.png')] bg-bottom bg-no-repeat">
        <HomePage/>
      </div>
      <div className="h-max bg-[url('https://cdn.ball-lickincats.com/images/bg-about.png')] bg-top bg-no-repeat">
        <AboutPage/>
      </div>
      <div className="h-max pt-[150px] bg-[url('https://cdn.ball-lickincats.com/images/bg-rectangle.png')] bg-top bg-no-repeat">
        <KucingSlide/>
      </div>
      <div className="h-max py-[150px] bg-[url('https://cdn.ball-lickincats.com/images/bg-rectangle-2.png')] bg-top bg-no-repeat bg-[length:auto_100%] bg-center bg-no-repeat-x relative z-10 flex flex-col justify-center">
        <Rarity />
        <div className="h-[250px] bg-[url('https://cdn.ball-lickincats.com/images/city-bush.png')] bg-bottom bg-no-repeat bg-[length:1800px_100%] bg-center bg-no-repeat-x absolute bottom-[-80px] w-[100vw]">
      
        </div>
      </div>
      <div className="h-[100vh] bg-screaminGreen">
      </div>
      <div className="h-[100vh] bg-[#825302] relative z-10">
        <div className="h-[250px] w-[500px] bg-[url('https://cdn.ball-lickincats.com/images/bush.png')] absolute top-[-150px] bg-no-repeat bg-contain right-[0]">
        
        </div>
      </div>
      <div className="h-[100vh] bg-[#FF6242] relative pb-[300px]">
      </div>
    </>

  )
}
